### ISSUE TITLE
Evaluation on Scannet.

### ISSUE THREAD

**Issue by wangm-buaa** [MisEty/RTG-SLAM#1]
Thank you for open-sourcing such an impressive work. I would like to conduct validation experiments on Scannet, but I haven't found the relevant configuration files. Could you provide some configuration file suggestions?

**Comment by MisEty** [comment]
We do not provide the configs of Scannet. Scannet contains various scenes with different scanning speeds, complexities and range. I think you can start by choosing a scene similar to the Replica Room for manually editing the configs, and ensure that objects in the scene are fully reflective. You might also need to increase the number of iterations to accommodate the noise in the input data.

I hope these suggestions are helpful to you!
