### ISSUE TITLE
关于pcd_densify.ply的可视化

### ISSUE THREAD

**Issue by YZWYD** [MisEty/RTG-SLAM#10]
请问训练结果中save_model/pcd_densify.ply是最终的训练模型吗？他该如何可视化呢？我使用SIBR_viewer可视化失败了。
将训练结果转移到windows系统我进行了如下尝试（replica/office3）：
1.不做任何处理，以管理员启动cmd运行SIBR_gaussianViewer_app.exe -m D:\Desk\RTG-SLAM-viewer\Replica\office3（replica\office1）
![1](https://github.com/MisEty/RTG-SLAM/assets/142296847/e1083224-1770-43fd-a4b4-ae821d7a6e95)
2.根据报错信息，我将pcd_densify.ply复制进point_cloud文件夹并重命名为point_cloud.ply再次运行（replica\office2）
<img width="678" alt="2" src="https://github.com/MisEty/RTG-SLAM/assets/142296847/e04b62fe-c253-4989-a45a-1a206ff8891a">
3.修改cfg_args为
Namespace(sh_degree=3,source_path='D:\Project\Datasets\Replica\office1',model_path='D:\Desk\RTG-SLAM-viewer\Replica\office1',images='images',resolution=-1,white_background=False,data_device='cuda',eval=False)
并将数据集中的office_mesh.ply复制到D:\Desk\RTG-SLAM-viewer\Replica\office1并重命名为input.ply再次运行（replica\office1）
<img width="1178" alt="3" src="https://github.com/MisEty/RTG-SLAM/assets/142296847/b3d2fb58-a987-43a4-93eb-942fbd46ec56">

**Comment by jeezrick** [comment]
https://github.com/Florian-Barthel/gaussian_viewer
我成功用这个可视化了。

**Comment by MisEty** [comment]
pcd_densify.ply是从高斯中采样提取的点云，用于测试几何精度的，不是最终的高斯模型
