### ISSUE TITLE
hotel数据处理完第一帧之后异常停止

### ISSUE THREAD

**Issue by Tokyo-dream** [MisEty/RTG-SLAM#11]
感谢分享目前GS-SLAM中最出色的方法，没有之一
<img width="537" alt="屏幕截图 2024-06-27 111920" src="https://github.com/MisEty/RTG-SLAM/assets/63401220/553aaa44-962a-45f2-95bc-f9bfbb6d7048">
![color_compare](https://github.com/MisEty/RTG-SLAM/assets/63401220/b1fb671d-93c4-4d62-8640-99cd664fc6cb)
处理之后，output中只有第0000帧的GS场景，问题定位在SLAM/multiprocess/tracker.py:236

**Comment by MisEty** [comment]
可能是后端的orbslam2有问题。您可以按照readme检查orbslam是否正常安装，或者在replica数据集上关闭后端优化进行测试

**Comment by chenqi13814529300** [comment]
> 感谢分享目前GS-SLAM中最出色的方法，没有之一 <img alt="屏幕截图 2024-06-27 111920" width="537" src="https://private-user-images.githubusercontent.com/63401220/343651952-553aaa44-962a-45f2-95bc-f9bfbb6d7048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTk5NjMsIm5iZiI6MTcyMjQ5OTY2MywicGF0aCI6Ii82MzQwMTIyMC8zNDM2NTE5NTItNTUzYWFhNDQtOTYyYS00NWYyLTk1YmMtZjliZmJiNmQ3MDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExN2Y2NjY5ZTBkMzc0OTU1YzVjOWJkN2ViYTllNTQ0MDcxZTgzODk3NzI5MjMxZTczNDE4ZWYzYTI0ZGFkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fwu3f6aPxJ0jpOE8zhp66uLSfcKNTFSzO98u4GkUDng"> ![color_compare](https://private-user-images.githubusercontent.com/63401220/343652336-b1fb671d-93c4-4d62-8640-99cd664fc6cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTk5NjMsIm5iZiI6MTcyMjQ5OTY2MywicGF0aCI6Ii82MzQwMTIyMC8zNDM2NTIzMzYtYjFmYjY3MWQtOTNjNC00ZDYyLTg2NDAtOTljZDY2NGZjNmNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDFlMWFhNTgyODFkN2VjYWVkZDM5ODcxODA5ZWIzMjdjZWFmMjRjMjY1ZGRkYjQzZmNiNTM2NDI4N2MxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oj9vdjfVTy6NyUPhnQdIUElIlWACwoMUqHyWf32r6Pg) 处理之后，output中只有第0000帧的GS场景，问题定位在SLAM/multiprocess/tracker.py:236

May I ask if you have solved it? I have also encountered this situation, but I have no problem running on public datasets, and it is the default configuration.

**Comment by Tokyo-dream** [comment]
是orbslam相关依赖的版本问题

**Comment by Tokyo-dream** [comment]
> > 感谢分享目前GS-SLAM中最出色的方法，没有之一 <img alt="屏幕截图 2024-06-27 111920" width="537" src="https://private-user-images.githubusercontent.com/63401220/343651952-553aaa44-962a-45f2-95bc-f9bfbb6d7048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTk5NjMsIm5iZiI6MTcyMjQ5OTY2MywicGF0aCI6Ii82MzQwMTIyMC8zNDM2NTE5NTItNTUzYWFhNDQtOTYyYS00NWYyLTk1YmMtZjliZmJiNmQ3MDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExN2Y2NjY5ZTBkMzc0OTU1YzVjOWJkN2ViYTllNTQ0MDcxZTgzODk3NzI5MjMxZTczNDE4ZWYzYTI0ZGFkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fwu3f6aPxJ0jpOE8zhp66uLSfcKNTFSzO98u4GkUDng"> ![color_compare](https://private-user-images.githubusercontent.com/63401220/343652336-b1fb671d-93c4-4d62-8640-99cd664fc6cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTk5NjMsIm5iZiI6MTcyMjQ5OTY2MywicGF0aCI6Ii82MzQwMTIyMC8zNDM2NTIzMzYtYjFmYjY3MWQtOTNjNC00ZDYyLTg2NDAtOTljZDY2NGZjNmNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA4MDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDFlMWFhNTgyODFkN2VjYWVkZDM5ODcxODA5ZWIzMjdjZWFmMjRjMjY1ZGRkYjQzZmNiNTM2NDI4N2MxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oj9vdjfVTy6NyUPhnQdIUElIlWACwoMUqHyWf32r6Pg) 处理之后，output中只有第0000帧的GS场景，问题定位在SLAM/multiprocess/tracker.py:236
> 
> May I ask if you have solved it? I have also encountered this situation, but I have no problem running on public datasets, and it is the default configuration.

是orbslam相关依赖的版本问题
