### ISSUE TITLE
Cuda out of memory error

### ISSUE THREAD

**Issue by Masrur02** [MisEty/RTG-SLAM#12]
In RTX 2060 GPU that has a 6 GB memory, the code can not be run due to memory issues. Is there any way to reduce the memory consumption while running the code?

TIA

**Comment by Masrur02** [comment]
I see reducing the image size might help, but it is still insufficient for RTX 2060. is there any other option to reduce the computation overload?

TIA

**Comment by MisEty** [comment]
You can try to decrease the sample number of Gaussians adding, or increase the frame step of dataset loading. Anyway, reducing the Gaussian number and reducing the rendering image size should reduce the overload.
