### ISSUE TITLE
关于points3d_depth.ply和point_cloud.py

### ISSUE THREAD

**Issue by YZWYD** [MisEty/RTG-SLAM#13]
很抱歉再次提问，我在训练过程及训练结束后遇到以下问题：
1.训练开始的时候会提示缺少points3d_depth.ply，我查看代码SLAM/utils.py第246行后根据我的个人理解将replica数据集场景中的类似office1.ply、room1.ply修改为points3d_depth.ply继续训练，如果我的理解和操作有错误还请指正。
<img width="658" alt="1" src="https://github.com/MisEty/RTG-SLAM/assets/142296847/8700f155-b1e5-4192-bedf-ad83554b03e9">
2.训练结束后output/dataset/Replica/office0/point_cloud文件夹是空文件夹。
<img width="842" alt="2" src="https://github.com/MisEty/RTG-SLAM/assets/142296847/8032df16-6467-4bad-a011-ab2e091b44a9">

**Comment by MisEty** [comment]
您好，这是为了对齐3DGS中sibr_viewer的接口。3DGS提供的sibr_viewer会默认读取point_cloud文件夹下的模型，并且读取一个名为input.ply的文件用于可视化。我们在测试的时候也按照这一需求添加了对应的代码，会在文件夹下创建一个point_cloud文件夹用于sibr_viewer读取模型，并且准备了每个数据集从深度图反投影得到的点云。这些问题并不会影响高斯模型的可视化，只是在sibr_viewer运行过程中会出现警告。
