### ISSUE TITLE
ORB-SLAM-PYBIND

### ISSUE THREAD

**Issue by ShreyaIAB** [MisEty/RTG-SLAM#15]
basically, i am executing line by line the commands in bash script. I get stuck here- 
![Capture](https://github.com/MisEty/RTG-SLAM/assets/156421818/af07fa59-549a-4c33-a7ee-3b591ad5110f)
![Capture](https://github.com/MisEty/RTG-SLAM/assets/156421818/afdaf178-aa08-4717-84a8-dd24f606a056)
this is how the folders are organised

**Comment by MisEty** [comment]
I'm not sure about the reason. It is suggested that you check the relevant documentation of CMake to set the search range of the OpenCV library.

**Comment by azuryl** [comment]
@ShreyaIAB you should sudo apt-get install opencv, it will update to  4.2
