### ISSUE TITLE
tum数据集psnr较低

### ISSUE THREAD

**Issue by Tokyo-dream** [MisEty/RTG-SLAM#17]
很感谢这篇出色的工作，我在Replica和Hotel数据集上都能得到较高质量的GS场景，但是tum数据集上表现较差，请问原因是什么，是否加一些Gaussian形状上的约束会好一点？
<img width="617" alt="屏幕截图 2024-07-02 111548" src="https://github.com/MisEty/RTG-SLAM/assets/63401220/44ed7ee1-2349-4fc6-858a-f82fcea5148f">
<img width="707" alt="屏幕截图 2024-07-02 111613" src="https://github.com/MisEty/RTG-SLAM/assets/63401220/9421eb91-d205-4d5e-b2f6-f782b32a04ff">

**Comment by jeezrick** [comment]
我也发现这样的情况。为什么论文中提到的改进方法在这个数据集上就不work了？

**Comment by MisEty** [comment]
我们的算法对深度噪声比较敏感，因为我们主要依赖新收集到的图像进行优化，在深度不一致的情况下会优化出几何和颜色有明显错误的高斯并且有可能被固定为稳定高斯，这会极大地影响后续的高斯添加和优化，添加形状上的正则项是一个可能的解决方案。
