### ISSUE TITLE
编译ORB-SLAM2出错

### ISSUE THREAD

**Issue by YZWYD** [MisEty/RTG-SLAM#2]
你好，首先感谢能够开源你的代码！
我在配置环境的时候运行bash build_orb.sh后报错提示找不到config.h，请问应该如何解决呢？
报错如下：
/home/zy/Project/RTG-SLAM/thirdParty/install/lib/libORB_SLAM2.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zy/Project/RTG-SLAM/thirdParty/pybind/build
Consolidate compiler generated dependencies of target orbslam2
make[2]: *** 没有规则可制作目标“/home/zy/Project/RTG-SLAM/thirdParty/install/lib/libORB_SLAM2.so”，由“/home/zy/Project/RTG-SLAM/thirdParty/pybind/lib/orbslam2.so” 需求。 停止。
make[2]: *** 正在等待未完成的任务....
[ 25%] Building CXX object CMakeFiles/orbslam2.dir/src/ORBSlamPython.cpp.o
In file included from /home/zy/Project/RTG-SLAM/thirdParty/pybind/src/ORB_SLAM2/Thirdparty/g2o/g2o/types/../core/optimizable_graph.h:37,
                 from /home/zy/Project/RTG-SLAM/thirdParty/pybind/src/ORB_SLAM2/Thirdparty/g2o/g2o/types/../core/base_vertex.h:30,
                 from /home/zy/Project/RTG-SLAM/thirdParty/pybind/src/ORB_SLAM2/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:37,
                 from /home/zy/Project/RTG-SLAM/thirdParty/pybind/src/ORB_SLAM2/Converter.h:27,
                 from /home/zy/Project/RTG-SLAM/thirdParty/pybind/src/ORBSlamPython.cpp:5:
/home/zy/Project/RTG-SLAM/thirdParty/pybind/src/ORB_SLAM2/Thirdparty/g2o/g2o/types/../core/openmp_mutex.h:30:10: fatal error: ../../config.h: 没有那个文件或目录
   30 | #include "../../config.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/orbslam2.dir/build.make:76：CMakeFiles/orbslam2.dir/src/ORBSlamPython.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/orbslam2.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

**Comment by MisEty** [comment]
我们自行克隆并重新编译了orbslam2模块并没有出现问题，您可以前往https://github.com/jskinn/ORB_SLAM2-PythonBindings,尝试原始版本的orbslam2-pythonbinding能否正常编译安装。

**Comment by MisEty** [comment]
或者您也可以提供build_orb.sh的所有的输出信息，我们帮您核对一下是否其他地方有问题

**Comment by YZWYD** [comment]
好的，因为pangolin和opencv编译并没有报错，所以我注释掉build_orb.sh中pangolin和opencv相关部分或再次运行，得到以下报错：
(RTG-SLAM) zy@zy:~/Project/RTG-SLAM$ bash build_orb.sh
/home/zy/anaconda3/envs/RTG-SLAM/lib/python3.9/site-packages/
build.sh: 行 1: $'\r'：未找到命令
Configuring and building Thirdparty/DBoW2 ...
build.sh: 行 5: $'\r'：未找到命令
build.sh: 第 6 行： cd: $'Thirdparty/DBoW2\r': 没有那个文件或目录
mkdir: 无法创建目录 “build\r”: 文件已存在
/CMakeCache.txt is different than the directory /home/zy/Project/RTG-SLAM/thirdParty/ORB-SLAM2-PYBIND/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


Build type: Release
-- Using flag -std=c++17.
-- OpenCV DIR:  /home/zy/Project/RTG-SLAM/thirdParty/install/lib/cmake/opencv4
-- OpenCV library status:
--     version: 4.2.0
--     libraries: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_gapi;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_stitching;opencv_video;opencv_videoio
--     include path: /home/zy/Project/RTG-SLAM/thirdParty/install/include/opencv4
-- Pangolin library status:
--     version: 0.5
--     libraries: 
--     include path: /home/zy/Project/RTG-SLAM/thirdParty/Pangolin/include;/home/zy/Project/RTG-SLAM/thirdParty/Pangolin/build/src/include;/usr/include;/usr/include;/usr/include;/usr/local/include/eigen3
-- Configuring incomplete, errors occurred!
/CMakeFiles/CMakeOutput.log".G-SLAM/thirdParty/ORB-SLAM2-PYBIND/build
make: “-j”选项需要正整数参数
用法：make [选项] [目标] ...
选项：
  -b, -m                      为兼容性而忽略。
  -B, --always-make           无条件制作 (make) 所有目标。
  -C 目录, --directory=目录    在执行前先切换到 <目录>。
  -d                          打印大量调试信息。
  --debug[=旗标]               打印各种调试信息。
  -e, --environment-overrides
                              环境变量覆盖 makefile 中的变量。
  --eval=字串               将 <字串> 作为 makefile 语句估值。
  -f 文件, --file=文件, --makefile=文件
                              从 <文件> 中读入 makefile。
  -h, --help                  打印该消息并退出。
  -i, --ignore-errors         忽略来自命令配方的错误。
  -I 目录, --include-dir=目录  在 <目录> 中搜索被包含的 makefile。
  -j [N], --jobs[=N]          同时允许 N 个任务；无参数表明允许无限个任务。
  -k, --keep-going            当某些目标无法制作时仍然继续。
  -l [N], --load-average[=N], --max-load[=N]
                              在系统负载高于 N 时不启动多任务。
  -L, --check-symlink-times   使用软链接及软链接目标中修改时间较晚的一个。
  -n, --just-print, --dry-run, --recon
                              只打印命令配方，不实际执行。
  -o 文件, --old-file=文件, --assume-old=文件
                              将 <文件> 当做很旧，不必重新制作。
  -O[类型], --output-sync[=类型]
                           使用 <类型> 方式同步并行任务输出。
  -p, --print-data-base       打印 make 的内部数据库。
  -q, --question              不运行任何配方；退出状态说明是否已全部更新。
  -r, --no-builtin-rules      禁用内置隐含规则。
  -R, --no-builtin-variables   禁用内置变量设置。
  -s, --silent, --quiet       不输出配方命令。
  -S, --no-keep-going, --stop
                              关闭 -k。
  -t, --touch                 touch 目标（更新修改时间）而不是重新制作它们。
  --trace                     打印跟踪信息。
  -v, --version               打印 make 的版本号并退出。
  -w, --print-directory       打印当前目录。
  --no-print-directory        关闭 -w，即使 -w 默认开启。
  -W 文件, --what-if=文件, --new-file=文件, --assume-new=文件
                              将 <文件> 当做最新。
  --warn-undefined-variables  当引用未定义变量的时候发出警告。

该程序为 x86_64-pc-linux-gnu 编译
报告错误到 <bug-make@gnu.org>
build.sh: 行 11: $'\r'：未找到命令
build.sh: 第 12 行： cd: $'../../g2o\r': 没有那个文件或目录
build.sh: 行 13: $'\r'：未找到命令
Configuring and building Thirdparty/g2o ...
build.sh: 行 15: $'\r'：未找到命令
mkdir: 无法创建目录 “build\r”: 文件已存在
/CMakeCache.txt is different than the directory /home/zy/Project/RTG-SLAM/thirdParty/ORB-SLAM2-PYBIND/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
make: “-j”选项需要正整数参数
用法：make [选项] [目标] ...
选项：
  -b, -m                      为兼容性而忽略。
  -B, --always-make           无条件制作 (make) 所有目标。
  -C 目录, --directory=目录    在执行前先切换到 <目录>。
  -d                          打印大量调试信息。
  --debug[=旗标]               打印各种调试信息。
  -e, --environment-overrides
                              环境变量覆盖 makefile 中的变量。
  --eval=字串               将 <字串> 作为 makefile 语句估值。
  -f 文件, --file=文件, --makefile=文件
                              从 <文件> 中读入 makefile。
  -h, --help                  打印该消息并退出。
  -i, --ignore-errors         忽略来自命令配方的错误。
  -I 目录, --include-dir=目录  在 <目录> 中搜索被包含的 makefile。
  -j [N], --jobs[=N]          同时允许 N 个任务；无参数表明允许无限个任务。
  -k, --keep-going            当某些目标无法制作时仍然继续。
  -l [N], --load-average[=N], --max-load[=N]
                              在系统负载高于 N 时不启动多任务。
  -L, --check-symlink-times   使用软链接及软链接目标中修改时间较晚的一个。
  -n, --just-print, --dry-run, --recon
                              只打印命令配方，不实际执行。
  -o 文件, --old-file=文件, --assume-old=文件
                              将 <文件> 当做很旧，不必重新制作。
  -O[类型], --output-sync[=类型]
                           使用 <类型> 方式同步并行任务输出。
  -p, --print-data-base       打印 make 的内部数据库。
  -q, --question              不运行任何配方；退出状态说明是否已全部更新。
  -r, --no-builtin-rules      禁用内置隐含规则。
  -R, --no-builtin-variables   禁用内置变量设置。
  -s, --silent, --quiet       不输出配方命令。
  -S, --no-keep-going, --stop
                              关闭 -k。
  -t, --touch                 touch 目标（更新修改时间）而不是重新制作它们。
  --trace                     打印跟踪信息。
  -v, --version               打印 make 的版本号并退出。
  -w, --print-directory       打印当前目录。
  --no-print-directory        关闭 -w，即使 -w 默认开启。
  -W 文件, --what-if=文件, --new-file=文件, --assume-new=文件
                              将 <文件> 当做最新。
  --warn-undefined-variables  当引用未定义变量的时候发出警告。

该程序为 x86_64-pc-linux-gnu 编译
报告错误到 <bug-make@gnu.org>
build.sh: 行 20: $'\r'：未找到命令
build.sh: 第 21 行： cd: $'../../../\r': 没有那个文件或目录
build.sh: 行 22: $'\r'：未找到命令
Uncompress vocabulary ...
build.sh: 行 24: $'\r'：未找到命令
build.sh: 第 25 行： cd: $'Vocabulary\r': 没有那个文件或目录
tar: ORBvoc.txt.tar.gz\r：无法 open: 没有那个文件或目录
tar: Error is not recoverable: exiting now
build.sh: 第 27 行： cd: $'..\r': 没有那个文件或目录
build.sh: 行 28: $'\r'：未找到命令
Configuring and building ORB_SLAM2 ...
build.sh: 行 30: $'\r'：未找到命令
mkdir: 无法创建目录 “build\r”: 文件已存在
CMake Warning:
  Ignoring extra path from command line:

"  "


" does not appear to contain CMakeLists.txt.Project/RTG-SLAM/thirdParty/ORB-SLAM2-PYBIND/build
Specify --help for usage, or press the help button on the CMake GUI.
: 没有那个文件或目录penCV_DIR=/home/zy/Project/RTG-SLAM/thirdParty/install/lib/cmake/opencv4
: 没有那个文件或目录MAKE_INSTALL_PREFIX=/home/zy/Project/RTG-SLAM/thirdParty/install
build.sh: 行 36: $'\r'：未找到命令
make: *** 没有规则可制作目标“install”。 停止。
Building B2 engine..

###
###
### Using 'gcc' toolset.
###
###

g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


###
###

> g++ -x c++ -std=c++11 -O2 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filesys.cpp filent.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam_strings.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp -o b2
tools/build/src/engine/b2
Detecting Python version... 3.9
Detecting Python root... /home/zy/anaconda3/envs/RTG-SLAM
Unicode/ICU support for Boost.Regex?... /usr
Backing up existing B2 configuration in project-config.jam.5
Generating B2 configuration in project-config.jam for gcc...

Bootstrapping is done. To build, run:

    ./b2
    
To generate header files, run:

    ./b2 headers

The configuration generated uses gcc to build by default. If that is
unintended either use the --with-toolset option or adjust configuration, by
editing 'project-config.jam'.

Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - B2 documentation:
     http://www.boost.org/build/

Performing configuration checks

    - default address-model    : 64-bit (cached) [1]
    - default architecture     : x86 (cached) [1]

[1] gcc-9

Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : not building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - json                     : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - nowide                   : not building
    - program_options          : not building
    - python                   : building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : not building
    - test                     : not building
    - thread                   : not building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...patience...
...patience...
...found 35050 targets...
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


Build type: Release
CXX17
-- Using flag -std=c++17.
CMake Deprecation Warning at cmake_modules/FindNumPy.cmake:32 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)


/home/zy/Project/RTG-SLAM/thirdParty/install/lib/libORB_SLAM2.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zy/Project/RTG-SLAM/thirdParty/pybind/build
Consolidate compiler generated dependencies of target orbslam2
make[2]: *** 没有规则可制作目标“/home/zy/Project/RTG-SLAM/thirdParty/install/lib/libORB_SLAM2.so”，由“/home/zy/Project/RTG-SLAM/thirdParty/pybind/lib/orbslam2.so” 需求。 停止。
make[2]: *** 正在等待未完成的任务....
[ 25%] Building CXX object CMakeFiles/orbslam2.dir/src/ORBSlamPython.cpp.o
/home/zy/Project/RTG-SLAM/thirdParty/pybind/src/ORBSlamPython.cpp:4:10: fatal error: ORB_SLAM2/KeyFrame.h: 没有那个文件或目录
    4 | #include <ORB_SLAM2/KeyFrame.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/orbslam2.dir/build.make:76：CMakeFiles/orbslam2.dir/src/ORBSlamPython.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/orbslam2.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

**Comment by YZWYD** [comment]
你好，我已经成功执行了步骤1.3 Modified ORB-SLAM2 Python Binding。是我的问题，在执行ORB-SLAM-PYBIND/build.sh的时候，可能是某些编码问题出现了换行符不识别的问题，导致本应该出现在thirdParty/install/include的ORB-SLAM2和一些其他文件出现在了其他地方，导致最后的编译安装失败。很抱歉给你们带来了麻烦。
另外我我还有以下两个问题
1.使用RTG-SLAM得到的模型应该如何可视化呢？
2.如何达到你们主页视频上那种使用RGBD相机进行实施渲染的效果呢？

**Comment by MisEty** [comment]
1. 我们使用的高斯模型和原始3DGS一致，训练得到的模型可以在3DGS的SIBR viewer中可视化
2. 我们的代码提供了根据相机参数进行渲染的接口，在训练过程中使用该函数即可得到您想要视角的渲染结果
