### ISSUE TITLE
Eigen3Config error

### ISSUE THREAD

**Issue by ShreyaIAB** [MisEty/RTG-SLAM#20]
**While running the  build.sh bash script**
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release \
         -DOpenCV_DIR=${opencv_dir} \
         -DCMAKE_INSTALL_PREFIX=${install_path}

i get the below error - 
![Capture](https://github.com/MisEty/RTG-SLAM/assets/156421818/56c96c6c-3067-473e-97aa-d3b2680a67fc)

How should i solve this error?

**Comment by ShreyaIAB** [comment]
i changed the RTG-SLAM\thirdParty\ORB-SLAM2-PYBIND\CMakeLists.txt 's 44 line from **find_package(Eigen3 3.4.0 REQUIRED NO_MODULE)** to **find_package(Eigen3 3.3.4 REQUIRED NO_MODULE)**. It solved the above error, but will it have any serious issues? Because now while running the build_orb.sh file - 

cd ../pybind
mkdir -p build && cd build

cmake .. -DPYTHON_INCLUDE_DIRS=${python_include} \
         -DPYTHON_LIBRARIES=${python_lib} \
         -DPYTHON_EXECUTABLE=${python_exe} \
         -DBoost_INCLUDE_DIRS=${install_path}/include/boost \
         -DBoost_LIBRARIES=${install_path}/lib/libboost_python39.so \
         -DORB_SLAM2_INCLUDE_DIR=${install_path}/include/ORB_SLAM2 \
         -DORB_SLAM2_LIBRARIES=${install_path}/lib/libORB_SLAM2.so \
         -DOpenCV_DIR=${install_path}/lib/cmake/opencv4 \
         -DPangolin_DIR=${install_path}/lib/cmake/Pangolin \
         -DPYTHON_NUMPY_INCLUDE_DIR=${numpy_include} \
         -DCMAKE_INSTALL_PREFIX=${python_env}

make install -j
I am getting still getting some errors and it fails in the end

**Comment by MisEty** [comment]
I am not sure what happened, maybe you can try to install the raw ORBSLAM2-pybind (https://github.com/jskinn/ORB_SLAM2-PythonBindings) first

**Comment by solomon-ma** [comment]
The Eigen version may cause the problem.  Please have a try.
