### ISSUE TITLE
请问最终模型是什么呢？

### ISSUE THREAD

**Issue by yoho131** [MisEty/RTG-SLAM#21]
不好意思，我是一名研0学生，刚刚开始3DGS的学习，想问问RTG-SLAM训练完场景后的最终高斯模型在哪里呢

**Comment by jeezrick** [comment]
在config里指定模型保存位置。如果你没有修改的话，在
![image](https://github.com/MisEty/RTG-SLAM/assets/47274616/878e609b-6a2d-4d61-8a17-2c102c0daad4)

**Comment by yoho131** [comment]
你好，可能是我的描述问题。我的意思是代码运行完毕后生成的可以在类似这种网站（https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php）可视化的.ply文件在哪里？
例如我训练完Replica/room0后在output/dataset/Replica/room0/save_model/frame_2000中似乎只有iter_1499_stable.ply和iter_1499_stable_sibr.ply，这是否代表这两个模型只是前1500张图片的训练结果？有完整的训练结果吗？

**Comment by MisEty** [comment]
iter_1499_stable_sibr.ply就是可以在原始3dgs的可视化的模型，1499并不代表训练的frame数量，而是优化的iter数量
