### ISSUE TITLE
读取数据的过程中爆内存

### ISSUE THREAD

**Issue by WangPei-hitman** [MisEty/RTG-SLAM#22]
![image](https://github.com/MisEty/RTG-SLAM/assets/58885413/ec4fc6f8-a9ef-469b-b086-373db581daed)
![image](https://github.com/MisEty/RTG-SLAM/assets/58885413/4ac511a2-c000-441d-a4ff-3a8e8c5c0ec1)
![image](https://github.com/MisEty/RTG-SLAM/assets/58885413/55de6568-c56c-40ab-8329-ed22927d2e31)
大佬您好，我在运行你们hotel数据集过程中每次读取一定量的图片内存都会超过我本机32GB的容量。是不是配置上哪里有什么问题?论文中的7.3G内存消耗的数据是如何评估出来的呢？

**Comment by ShreyaIAB** [comment]
@WangPei-hitman 您能帮我走到这一步吗？

**Comment by MisEty** [comment]
7.3G是指训练过程中消耗的显存。为了提高速度我们采用了先把一次性所有图片读入内存，在训练过程中不再反复读取本体图片的方式，此处的内存消耗与算法无关。因为数据集规模较大所以消耗的内存可能较多，您可以降低分辨率或者测试规模较小的数据集replica，也可以稍微修改代码使其在训练过程中读取图片。
