### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by canyou2014** [MisEty/RTG-SLAM#27]
I build success. but run with error:
““”
import orbslam2
ImportError: libopencv_highgui.so.4.2: cannot open shared object file: No such file or directory
“”“
libopencv_highgui.so.4.2 is already in install/lib

**Comment by Launch-on-Titania** [comment]
The issue arises because your path lacks the correct indexing. 
You can manually export the necessary path by executing the following command:

```
export LD_LIBRARY_PATH=/your-path/RTG-SLAM/thirdParty/install/lib:$LD_LIBRARY_PATH
```
