### ISSUE TITLE
How can I run it on my own captured datasets?

### ISSUE THREAD

**Issue by laliwang** [MisEty/RTG-SLAM#29]
Thanks for your excellent work and sharing! Since I want to use it for my own captured datasets or other open-source practical datasets such as the ScanNet, I just wonder which files I need to modify including the configs for SLAM and ORB-SLAM2. Thank you sincerely!

**Comment by MisEty** [comment]
You can refer to [capture data](https://github.com/MisEty/RTG-SLAM/issues/23) on how to capture data. However, we do not provide parameters for running on other datasets; you can adjust them yourself.
