### ISSUE TITLE
ValueError: string is not a file: /data/azuryl/RTG-SLAM/data/Replica/office0/office0.ply

### ISSUE THREAD

**Issue by azuryl** [MisEty/RTG-SLAM#30]
/data/azuryl/RTG-SLAM$ python metric.py --config ./configs/replica/office0.yaml
check frame:  frame_2000
Assuming Replica data set! [24/07 13:14:11]
Reading camera 2000/2000 [24/07 13:14:56]
select models ['iter_1139_stable.ply'] [24/07 13:14:56]
test_iter:  1139 [24/07 13:14:56]
geometry eval ply:  output/dataset/Replica/office0/save_model/pcd_densify.ply [24/07 13:14:56]
Evaluating:   0%|                                                                                                                                                                       | 0/2000 [00:00<?, ?it/s]valid pixel ratio=96.18%, color loss=0.005, depth loss=0.633cm, normal loss=0.000, psnr=39.783 [24/07 13:14:57]
Evaluating:   0%|                                                                                                                                                               | 1/2000 [00:00<23:25,  1.42it/s]valid pixel ratio=96.10%, color loss=0.005, depth loss=0.628cm, normal loss=0.000, psnr=39.579 [24/07 13:14:57]
valid pixel ratio=96.00%, color loss=0.005, depth loss=0.627cm, normal loss=0.000, psnr=39.446 [24/07 13:14:57]
valid pixel ratio=95.92%, color loss=0.005, depth loss=0.627cm, normal loss=0.000, psnr=39.178 [24/07 13:14:57]
valid pixel ratio=95.83%, color loss=0.005, depth loss=0.617cm, normal loss=0.000, psnr=39.006 [24/07 13:14:57]
Evaluating:   0%|▍                                                                                                                                                              | 5/2000 [00:00<04:16,  7.78it/s]valid pixel ratio=95.75%, color loss=0.005, depth loss=0.616cm, normal loss=0.000, psnr=38.884 [24/07 13:14:57]
valid pixel ratio=95.68%, color loss=0.005, depth loss=0.617cm, normal loss=0.000, psnr=39.179 [24/07 13:14:57]
valid pixel ratio=95.63%, color loss=0.005, depth loss=0.612cm, normal loss=0.000, psnr=39.443 [24/07 13:14:57]
valid pixel ratio=95.63%, color loss=0.005, depth loss=0.608cm, normal loss=0.000, psnr=39.560 [24/07 13:14:57]
valid pixel ratio=95.62%, color loss=0.005, depth loss=0.607cm, normal loss=0.000, psnr=39.680 [24/07 13:14:57]
Evaluating:   0%|▊                                                                                                                                                             | 10/2000 [00:00<02:06, 15.75it/s]valid pixel ratio=95.61%, color loss=0.005, depth loss=0.607cm, normal loss=0.000, psnr=39.737 [24/07 13:14:57]
valid pixel ratio=95.62%, color loss=0.005, depth loss=0.607cm, normal loss=0.000, psnr=39.817 [24/07 13:14:57]
valid pixel ratio=95.64%, color loss=0.005, depth loss=0.610cm, normal loss=0.000, psnr=39.815 [24/07 13:14:57]
valid pixel ratio=95.63%, color loss=0.005, depth loss=0.609cm, normal loss=0.000, psnr=39.890 [24/07 13:14:57]
valid pixel ratio=95.63%, color loss=0.005, depth loss=0.613cm, normal loss=0.000, psnr=39.929 [24/07 13:14:57]
valid pixel ratio=95.64%, color loss=0.005, depth loss=0.617cm, normal loss=0.000, psnr=39.886 [24/07 13:14:57]
Evaluating:   1%|█▎                                                                                                                                                            | 16/2000 [00:01<01:21, 24.29it/s]valid pixel ratio=95.66%, color loss=0.005, depth loss=0.617cm, normal loss=0.000, psnr=39.940 [24/07 13:14:58]
valid pixel ratio=95.65%, color loss=0.005, depth loss=0.620cm, normal loss=0.000, psnr=39.975 [24/07 13:14:58]
valid pixel ratio=95.67%, color loss=0.005, depth loss=0.623cm, normal loss=0.000, psnr=39.914 [24/07 13:14:58]
valid pixel ratio=95.67%, color loss=0.005, depth loss=0.624cm, normal loss=0.000, psnr=39.921 [24/07 13:14:58]
valid pixel ratio=95.69%, color loss=0.005, depth loss=0.629cm, normal loss=0.000, psnr=39.956 [24/07 13:14:58]
valid pixel ratio=95.69%, color loss=0.005, depth loss=0.629cm, normal loss=0.000, psnr=39.857 [24/07 13:14:58]
Evaluating:   1%|█▋                                                                                                                                                            | 22/2000 [00:01<01:03, 31.22it/s]valid pixel ratio=95.68%, color loss=0.005, depth loss=0.629cm, normal loss=0.000, psnr=39.865 [24/07 13:14:58]
valid pixel ratio=95.71%, color loss=0.005, depth loss=0.631cm, normal loss=0.000, psnr=39.824 [24/07 13:14:58]
valid pixel ratio=95.72%, color loss=0.005, depth loss=0.633cm, normal loss=0.000, psnr=39.792 [24/07 13:14:58]
valid pixel ratio=95.75%, color loss=0.005, depth loss=0.636cm, normal loss=0.000, psnr=39.669 [24/07 13:14:58]
valid pixel ratio=95.78%, color loss=0.005, depth loss=0.631cm, normal loss=0.000, psnr=39.486 [24/07 13:14:58]
valid pixel ratio=95.82%, color loss=0.005, depth loss=0.637cm, normal loss=0.000, psnr=39.354 [24/07 13:14:58]
Evaluating:   1%|██▏                                                                                                                                                           | 28/2000 [00:01<00:53, 36.71it/s]valid pixel ratio=95.85%, color loss=0.005, depth loss=0.637cm, normal loss=0.000, psnr=39.369 [24/07 13:14:58]
valid pixel ratio=95.92%, color loss=0.005, depth loss=0.645cm, normal loss=0.000, psnr=39.540 [24/07 13:14:58]
valid pixel ratio=95.97%, color loss=0.005, depth loss=0.643cm, normal loss=0.000, psnr=39.535 [24/07 13:14:58]
valid pixel ratio=96.02%, color loss=0.005, depth loss=0.650cm, normal loss=0.000, psnr=39.569 [24/07 13:14:58]
valid pixel ratio=96.07%, color loss=0.005, depth loss=0.655cm, normal loss=0.000, psnr=39.631 [24/07 13:14:58]
valid pixel ratio=96.11%, color loss=0.005, depth loss=0.655cm, normal loss=0.000, psnr=39.697 [24/07 13:14:58]
Evaluating:   2%|██▋           

Evaluating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 1995/2000 [00:44<00:00, 44.73it/s]valid pixel ratio=93.99%, color loss=0.008, depth loss=1.020cm, normal loss=0.000, psnr=35.563 [24/07 13:15:41]
valid pixel ratio=93.98%, color loss=0.008, depth loss=1.023cm, normal loss=0.000, psnr=35.537 [24/07 13:15:41]
valid pixel ratio=94.00%, color loss=0.008, depth loss=1.029cm, normal loss=0.000, psnr=35.539 [24/07 13:15:41]
valid pixel ratio=93.99%, color loss=0.008, depth loss=1.027cm, normal loss=0.000, psnr=35.504 [24/07 13:15:41]
valid pixel ratio=94.06%, color loss=0.008, depth loss=1.033cm, normal loss=0.000, psnr=35.459 [24/07 13:15:41]
Evaluating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 1999/2000 [00:44<00:00, 45.09it/s]
Traceback (most recent call last):
  File "/data/azuryl/RTG-SLAM/metric.py", line 223, in <module>
    main()
  File "/data/azuryl/RTG-SLAM/metric.py", line 187, in main
    losses = eval_frame(
  File "/data/azuryl/RTG-SLAM/SLAM/eval.py", line 266, in eval_frame
    pcd_losses = eval_pcd(
  File "/data/azuryl/RTG-SLAM/SLAM/eval.py", line 184, in eval_pcd
    mesh_gt = trimesh.load(gt_meshfile, process=False)
  File "/home/azuryl/anaconda3/envs/RTG/lib/python3.9/site-packages/trimesh/exchange/load.py", line 114, in load
    ) = _parse_file_args(file_obj=file_obj, file_type=file_type, resolver=resolver)
  File "/home/azuryl/anaconda3/envs/RTG/lib/python3.9/site-packages/trimesh/exchange/load.py", line 612, in _parse_file_args
    raise ValueError(f"string is not a file: {file_obj}")
ValueError: string is not a file: /data/azuryl/RTG-SLAM/data/Replica/office0/office0.ply

**Comment by MisEty** [comment]
This is for evaluating geometric accuracy, which requires reading the ground truth model for comparison. You can directly comment out this section of the code.
