### ISSUE TITLE
Can't do a git clone

### ISSUE THREAD

**Issue by notu97** [MisEty/RTG-SLAM#31]
I am getting this error while trying to git clone the repo:

`Cloning into 'RTG-SLAM'...
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 96 (delta 19), reused 28 (delta 18), pack-reused 58
Unpacking objects: 100% (96/96), 18.89 MiB | 16.40 MiB/s, done.
Submodule 'submodules' (git@github.com:CJAPPLE5/RTG-SLAM-cuda_utils.git) registered for path 'submodules'
Submodule 'thirdParty/ORB-SLAM2-PYBIND' (git@github.com:CJAPPLE5/RTG-SLAM-BACKEND.git) registered for path 'thirdParty/ORB-SLAM2-PYBIND'
Submodule 'thirdParty/pybind' (git@github.com:CJAPPLE5/RTG-SLAM-PYBIND.git) registered for path 'thirdParty/pybind'
Cloning into '/home/shiladitya/Projects/RTG-SLAM/submodules'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:CJAPPLE5/RTG-SLAM-cuda_utils.git' into submodule path '/home/shiladitya/Projects/RTG-SLAM/submodules' failed
Failed to clone 'submodules'. Retry scheduled
Cloning into '/home/shiladitya/Projects/RTG-SLAM/thirdParty/ORB-SLAM2-PYBIND'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:CJAPPLE5/RTG-SLAM-BACKEND.git' into submodule path '/home/shiladitya/Projects/RTG-SLAM/thirdParty/ORB-SLAM2-PYBIND' failed
Failed to clone 'thirdParty/ORB-SLAM2-PYBIND'. Retry scheduled
Cloning into '/home/shiladitya/Projects/RTG-SLAM/thirdParty/pybind'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:CJAPPLE5/RTG-SLAM-PYBIND.git' into submodule path '/home/shiladitya/Projects/RTG-SLAM/thirdParty/pybind' failed
Failed to clone 'thirdParty/pybind'. Retry scheduled
Cloning into '/home/shiladitya/Projects/RTG-SLAM/submodules'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:CJAPPLE5/RTG-SLAM-cuda_utils.git' into submodule path '/home/shiladitya/Projects/RTG-SLAM/submodules' failed
Failed to clone 'submodules' a second time, aborting
`

**Comment by azuryl** [comment]
you should set ssh key in github
