### ISSUE TITLE
Question about the ablation study on SH coefficient

### ISSUE THREAD

**Issue by YRong-FD** [MisEty/RTG-SLAM#34]
Thanks for your great work. I tried to reproduce the ablation study on SH coefficients. In the paper, the PSNR is decreased from 35.43 to 33.90 in Replica dataset, which is about 1.5dB difference. I tried to reproduce this by setting  `active_sh_degree` and `max_sh_degree` both to 0 in the `base.yaml` without ORB-SLAM2 backend. But I only get an average decrease from 34.86 to 34.76 which is only about 0.1dB. Are there any mistakes I made?

Here is the individual scene data:

before setting sh_degree to 0:
|     | PSNR     | SSIM     | LPIPS    |
| --- | -------- | -------- | -------- |
| office0    | 39.31817 | 0.989591 | 0.080613 |
| office1    | 39.43873 | 0.990091 | 0.097743 |
| office2    | 32.82746 | 0.981165 | 0.139322 |
| office3    | 32.49909 | 0.981976 | 0.135881 |
| office4    | 35.74929 | 0.984928 | 0.120904 |
| room0    | 31.08662 | 0.964942 | 0.145441 |
| room1    | 33.51214 | 0.975605 | 0.1145   |
| room2    | 34.6558  | 0.981277 | 0.122791 |
| mean    | 34.88591 | 0.981197 | 0.119649 |

After setting sh_degree to 0:
|         | PSNR     | SSIM     | LPIPS    |
| ------- | -------- | -------- | -------- | 
| office0 | 39.17187|0.989056|0.081168|
| office1 | 39.38024|0.990061|0.097865|
| office2 | 32.6095|0.980215|0.141946|
| office3 | 32.27849|0.980225|0.138818|
| office4 | 35.49198|0.984076|0.122714|
| room0   | 30.76742|0.962122|0.150585|
| room1   | 33.71112|0.977145|0.1148|
| room2   | 34.64019|0.98203|0.116688|
| mean    | 34.75635|0.980616|0.120573|

**Comment by MisEty** [comment]
Hello, I apologize for the delayed response to your question. In the released version, we follow the original 3DGS settings, where the default learning rate for higher-order SH is set to 1/20 of that for first-order SH. This makes it difficult to learn higher-order SH in the SLAM data. You can try to increase the learning rate for higher-order SH to conduct experiments.
