### ISSUE TITLE
The hotel cannot run?

### ISSUE THREAD

**Issue by chenqi13814529300** [MisEty/RTG-SLAM#35]
The hotel cannot run, but the public dataset replica can run normally (all with default configuration) and obtain correct results. But I really want to know how to run your self-made dataset, because I also want to create my own dataset and run it on your algorithm. I really hope to get your help.

**Comment by chenqi13814529300** [comment]
![image](https://github.com/user-attachments/assets/0aee3440-d59c-4122-884c-7a955957f45b)

**Comment by ttsesm** [comment]
@chenqi13814529300 did you manage to have it running on the hotel dataset?

I am also interested to use it on my own dataset. Actually I am only interested to check the gaussian optimizer and how fast and robust is in comparison to the original gaussian splatting optimizer.

**Comment by chenqi13814529300** [comment]
> 您是否设法让它在酒店数据集上运行？
> 
> 我也有兴趣在我自己的数据集上使用它。实际上，我只对检查高斯优化器感兴趣，以及与原始高斯溅射优化器相比，它的速度和鲁棒性如何。

It can run on the hotel's dataset, but it cannot be due to my environment configuration issues before. The rendering ability of this algorithm is definitely not comparable to the Gaussian algorithm based on 3D reconstruction, but this algorithm has some advantages in speed.

**Comment by chenqi13814529300** [comment]
> @chenqi13814529300 did you manage to have it running on the hotel dataset?
> 
> I am also interested to use it on my own dataset. Actually I am only interested to check the gaussian optimizer and how fast and robust is in comparison to the original gaussian splatting optimizer.

It can run on the hotel's dataset, but it cannot be due to my environment configuration issues before. The rendering ability of this algorithm is definitely not comparable to the Gaussian algorithm based on 3D reconstruction, but this algorithm has some advantages in speed.

**Comment by ttsesm** [comment]
I see, thanks for the reply. Indeed, the environment configuration is a bit tricky to arrange. I have also managed to have it somehow working and I agree both that there are advantages in the speed while the rendering accuracy is not perfect but still quite promising.

I will try to experiment a bit more, the whole solution looks quite nice.
