### ISSUE TITLE
frame_step is 10 error

### ISSUE THREAD

**Issue by chenqi13814529300** [MisEty/RTG-SLAM#36]
frame_step: 0 =>frame_step: 10
running error:
RuntimeError: CUDA error: invalid configuration argument CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE

when frame_step is correct and os.environ["CUDA_VISIBLE_DEVICES"] = "0"

**Comment by MisEty** [comment]
It seems to be a memory issue caused by parameter tuning. You might consider debugging it yourself.
