### ISSUE TITLE
depthImag  is significant?

### ISSUE THREAD

**Issue by chenqi13814529300** [MisEty/RTG-SLAM#37]
The next question may be a bit silly:
1. Does the accuracy of depth maps have a significant impact on training
2. If we obtain point clouds for each frame, can we only convert this point cloud into a depth map

**Comment by MisEty** [comment]
1. Yes
2. It depends on the density of the point cloud. Our algorithm is based on the depth observation of each pixel, so if the point cloud can render the depth of each pixel, it is ok.
