### ISSUE TITLE
can not find config.yaml of tum dataset

### ISSUE THREAD

**Issue by wanglong1008** [MisEty/RTG-SLAM#4]
when I run  python slam.py --config ./configs/tum/fr1_desk.yaml,I got error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wanglong/RTG-SLAM/data/TUM_RGBD/rgbd_dataset_freiburg1_desk/config.yaml'

**Comment by MisEty** [comment]
I'm sorry that we missed some configs! Please refer the updated readme to solve this problem.
