### ISSUE TITLE
model flipped left and right

### ISSUE THREAD

**Issue by chenqi13814529300** [MisEty/RTG-SLAM#40]
Replace the RGB camera with an RGB camera and generate the depth map yourself. What changes need to be made based on your framework. The depth map I rendered is basically correct, but the saved model seems to have flipped left and right.
![image](https://github.com/user-attachments/assets/45578d54-13ce-47b9-b120-a183d76e3239)

**Comment by MisEty** [comment]
I didn't fully understand your question, but in some datasets, the camera intrinsics and images are indeed flipped. You might consider flipping the images or manually flipping the Gaussian model.
