### ISSUE TITLE
请问如何才能实现可视化SLAM建图

### ISSUE THREAD

**Issue by Lumingfei0616** [MisEty/RTG-SLAM#42]
您好，非常感谢您开源了如此优秀的作品。

我的问题如下，我按照您给的readme.md中的步骤，使用python slam.py --config ./configs/tum/fr1_desk.yaml这条命令进行训练，但是最终的结果如下：

[LOG] stable num: 277593, unstable num: 30779 [01/09 16:51:14]
[LOG] processed frame:  [0, 3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67, 71, 75, 79, 83, 87, 91, 95, 99, 103, 107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155, 159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199, 203, 207, 211, 215, 219, 223, 227, 231, 235, 239, 243, 247, 251, 255, 259, 263, 267, 271, 275, 279, 283, 287, 291, 295, 299, 303, 307, 311, 315, 319, 323, 327, 331, 335, 339, 343, 347, 351, 355, 359, 363, 367, 371, 375, 379, 383, 387, 391, 395, 399, 403, 407, 411, 415, 419, 423, 427, 431, 435, 439, 443, 447, 451, 455, 459, 463, 467, 471, 475, 479, 483, 487, 491, 495, 499, 503, 507, 511, 515, 519, 523, 527, 531, 535, 539, 543, 547, 551, 555, 559, 563, 567, 571, 575, 579, 583, 587, 591] [01/09 16:51:14]
[LOG] keyframes:  [0, 23, 39, 63, 83, 111, 123, 139, 163, 175, 183, 187, 215, 259, 267, 275, 283, 299, 319, 327, 339, 343, 347, 355, 363, 371, 379, 399, 443, 459, 491, 507, 531, 563] [01/09 16:51:14]
[LOG] mean tracker process time:  0.08090082978880084 [01/09 16:51:14]
[LOG] mean mapper process time:  0.18468919678314313 [01/09 16:51:14]
===== global optimize ===== [01/09 16:51:14]
keyframe num = 34, stable gaussian num = 308372 [01/09 16:51:14]
global optimization: 100%|**************| 340/340 [00:05<00:00, 61.12it/s, loss=0.04900]
valid pixel ratio=79.20%, color loss=0.055, depth loss=2.731cm, normal loss=0.000, psnr=20.722 [01/09 16:51:20]
100%|************|:  1.495585417059479 [01/09 16:51:26]

我想咨询一下您，如何实现您们开源作品网站中的相同效果：
![屏幕截图 2024-09-01 174027](https://github.com/user-attachments/assets/c34b3af6-bf8c-4747-a628-896dc2cfdfd2)

对应的链接是https://gapszju.github.io/RTG-SLAM/static/videos/Supplementary_Video_Sub_01.mp4

**Comment by Lumingfei0616** [comment]
同时，在执行python slam.py --config ./configs/tum/fr1_desk.yaml 该命令的时候，我发现最开始出现了一个报错：
cp: cannot stat 'data/TUM_RGBD/rgbd_dataset_freiburg1_desk/points3d_depth.ply': No such file or directory

请问是不是由于我没有points3d_depth.ply这个文件，才导致不能实现上面提到的动态可视化效果呢？如果是的话，那么我应该怎么解决呢？如果不是的话，这个缺失的文件是会对其他部分产生影响吗？

以下是终端执行命令的最开始输出部分：
(RTG) root@autodl-container-362e44a99f-85fb0714:~/autodl-tmp/RTG-SLAM# python slam.py --config ./configs/tum/fr1_desk.yaml
Assuming TUM data set! [01/09 16:48:17]
Reading camera 592/592 [01/09 16:48:26]
output/dataset/TUM_RGBD/fr1_desk [01/09 16:48:26]
init orb backend [01/09 16:48:26]

ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!


Camera Parameters: 
- fx: 517.306
- fy: 516.469
- cx: 318.643
- cy: 255.314
- k1: 0.262383
- k2: -0.953104
- k3: 1.16331
- p1: -0.005358
- p2: 0.002628
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Depth Threshold (Close/Far Points): 3.09294
data/TUM_RGBD/rgbd_dataset_freiburg1_desk [01/09 16:48:31]
cp: cannot stat 'data/TUM_RGBD/rgbd_dataset_freiburg1_desk/points3d_depth.ply': No such file or directory
 [01/09 16:48:32]
========== curr frame is: 0 ========== [01/09 16:48:32]
 [01/09 16:48:32]
/root/miniconda3/envs/RTG/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525539683/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
New map created with 923 points
[LOG] tracker cost time: 0.4679889678955078 [01/09 16:48:32]
===== map optimize ===== [01/09 16:48:32]

**Comment by MisEty** [comment]
您好，在线可视化程序我们目前还没有开源，您可以通过在重建过程中实时保存高斯渲染的图片用于可视化检查。具体可以参考这个issue的内容：
https://github.com/MisEty/RTG-SLAM/issues/7
