### ISSUE TITLE
请问如何使用自己的数据进行测试？

### ISSUE THREAD

**Issue by dandelion-chu** [MisEty/RTG-SLAM#44]
您好，非常感谢您的优秀工作，我这边按照步骤进行了环境部署，然后测试了hotel和tum desk1的数据集，如下图所示，感觉TUM的数据集效果很差，hotel看起来还可以，请问这个是正常的吗？还有就是如果想使用自己的设备录取数据，需要怎么操作呢，需要提供哪些数据和文件？然后如果想要渲染效果丰富，是不是各个角度都要尽量都拍摄到才行？谢谢，期待您的指教~
![1](https://github.com/user-attachments/assets/3aa7f1e4-4471-416a-b087-257512d22592)
![2](https://github.com/user-attachments/assets/b42bab08-7b55-406f-b9ac-2e05f1597f05)

**Comment by MisEty** [comment]
您好，TUM数据集的效果较差是正常的，我们的算法对深度较为敏感，如果深度出现明显的噪声和错误会导致高斯的几何也发生错误。如果要在自己的数据上使用可以参考我们的hotel数据集上的数据格式，但根据扫描速度和设备帧数可能需要适当调整参数。

**Comment by dandelion-chu** [comment]
> 您好，TUM数据集的效果较差是正常的，我们的算法对深度较为敏感，如果深度出现明显的噪声和错误会导致高斯的几何也发生错误。如果要在自己的数据上使用可以参考我们的hotel数据集上的数据格式，但根据扫描速度和设备帧数可能需要适当调整参数。

明白了，非常感谢~~
