### ISSUE TITLE
paper中render depth对应代码

### ISSUE THREAD

**Issue by AutoSenseTech** [MisEty/RTG-SLAM#5]
非常感谢开源和你们的工作。也恭喜你的paper中了siggraph2024.
我想问一下paper中render depth 需要找intersection的代码再哪里，还有公式4和公式5再哪里？

感谢。

**Comment by MisEty** [comment]
公式4和公式5都是深度渲染的流程，在[forward.cu](https://github.com/CJAPPLE5/RTG-SLAM-cuda_utils/blob/24dcf0aec00f35229f247ac206a5c0b141e15991/diff-gaussian-rasterizer-depth/cuda_rasterizer/forward.cu)中的renderCUDA函数里您可以参考。
