### ISSUE TITLE
Question regarding the gaussian_release function in the Mapper.py

### ISSUE THREAD

**Issue by EryiXie** [MisEty/RTG-SLAM#50]
Hi, I have a question regarding the gaussian_release function in the Mapper.py:

https://github.com/MisEty/RTG-SLAM/blob/e38240b855bac5081d8f7eb2d23997712073b3ec/SLAM/multiprocess/mapper.py#L275-L284

If I understand the part about State Management in the paper correctly: 
![image](https://github.com/user-attachments/assets/b9567be0-2115-441b-8528-22976ec6235e)

Stable Gaussians with an accumulated color error larger than a certain threshold and its accumulated depth error is less than another threshold,  should be released to Unstable Gaussian. However, they are concatenated back to the Stable Gaussians from the implementation.

It confuses me a lot.  Did I miss or misunderstand something?

**Comment by MisEty** [comment]
Thank you for your reminder. It seems to be a mistake while re-organizing the code (the comment for this function was wrong). The concatenation should be performed on unstable_gaussians!
