### ISSUE TITLE
Question about Geometry Results and Reproducing Table 3 Metrics

### ISSUE THREAD

**Issue by cpfy** [MisEty/RTG-SLAM#54]
Hello!

First of all, thank you for sharing such a solid piece of work! 

I’ve integrated a TSDF-based mesh extraction (approach from [Point-SLAM](https://github.com/eriksandstroem/Point-SLAM/blob/main/src/tools/get_mesh_tsdf_fusion.py) as mentioned in paper) and tested it on the Replica/office0 dataset, but the resulting mesh (left image) shows significant surface irregularities (e.g., bumps and uneven areas).

- Is this geometry result expected? or could there be issues in my adaptation of the TSDF-based mesh extraction?
- Additionally, could you share any code or guidance for reproducing the geometry accuracy metrics in Table 3 (right image)?

Looking forward to your response, and thank you again for this amazing work!

![](https://github.com/user-attachments/assets/531c5a74-3421-4c5e-99c4-631eae3b78ba)

**Comment by MisEty** [comment]
As mentioned in our paper, we generate point clouds for RTG-SLAM and SplatTAM by sampling on the Gaussians. The sampling function is https://github.com/MisEty/RTG-SLAM/blob/main/SLAM/gaussian_pointcloud.py#L53, and we save the densified point cloud in `train.py`. We also provide the evalution function https://github.com/MisEty/RTG-SLAM/blob/main/SLAM/eval.py#L226 to reproduce the results.
