### ISSUE TITLE
这行代码是否有误？

### ISSUE THREAD

**Issue by zengliangjun** [MisEty/RTG-SLAM#6]
diff --git a/SLAM/multiprocess/mapper.py b/SLAM/multiprocess/mapper.py
index b376f66..ecd0295 100755
--- a/SLAM/multiprocess/mapper.py
+++ b/SLAM/multiprocess/mapper.py
@@ -863,7 +863,7 @@ class Mapping(object):
         
         stable_normal_check = self.stable_pointcloud.get_normal[intersect_stable_index]
         stable_xyz_check = self.stable_pointcloud.get_xyz[intersect_stable_index]
-        unstable_xyz_check = self.temp_pointcloud.get_xyz[indices]
+        unstable_xyz_check = unstable_xyz[indices]
         point_to_plane_distance = (
             (stable_xyz_check - unstable_xyz_check) * stable_normal_check
         ).sum(dim=-1)

请教一下，这一行是否有误呀！
应该为 unstable_xyz

**Comment by MisEty** [comment]
不好意思没有看明白您的问题，可以具体描述一下您想要修改的是哪一行

**Comment by zengliangjun** [comment]
代码  SLAM/multiprocess/mapper.py

- [833 ] unstable_xyz = self.temp_pointcloud.get_xyz
-  ...
- [837 ] unstable_xyz = unstable_xyz[unstable_opacity_filter]
-  ...
- [839 ] indices = torch.arange(unstable_xyz.shape[0]).cuda().long()
-  ...
- [866 ] unstable_xyz_check = self.temp_pointcloud.get_xyz[indices]

indices 对应是  unstable_xyz 的索引，在使用的时侯用的是 self.temp_pointcloud。
在 837 行  unstable_xyz 与 self.temp_pointcloud 己经不一样了。
所以我理解  866 行应该改为
unstable_xyz_check = unstable_xyz[indices]
才是正解的。

不知道这样理解对不对？

**Comment by MisEty** [comment]
在这个函数中，我们对`temp_pointcloud`进行筛选，`temp_pointcloud`是每帧新添加的高斯点，而此时这些点都是不透明的（参考[add_empty_points](https://github.com/MisEty/RTG-SLAM/blob/main/SLAM/gaussian_pointcloud.py#L305)），因此L837并不会筛选掉任何高斯，`self.temp_pointcloud.get_xyz`和`unstable_xyz`相同，并不会出现您说的问题。
很抱歉我们在整理代码的过程中出现了错误导致了理解上的困难，感谢您的提醒，我们之后会修改这段代码使其不再产生歧义。
